# Generated by Django 3.2.1 on 2021-08-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlaItsupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(verbose_name='Periode')),
                ('unit', models.CharField(max_length=32)),
                ('spesifikasi', models.CharField(choices=[('AN', 'Analyst'), ('FE', 'Field Engineer'), ('FS', 'Field Support')], default='FS', max_length=32)),
                ('personil', models.CharField(max_length=128)),
                ('total_ticket', models.IntegerField()),
                ('tiket_over_sla', models.IntegerField()),
                ('pencapaian_sla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('durasi_over', models.DecimalField(decimal_places=2, max_digits=5)),
                ('biaya_restitusi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penempatan', models.CharField(max_length=64)),
                ('asman', models.CharField(max_length=32)),
                ('mulai_bekerja', models.DateField()),
                ('total_biaya', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
