# Generated by Django 3.2.1 on 2021-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_alter_network_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='employee_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='memory',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='computer',
            name='monitor',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='itsupport',
            name='jobdescription',
            field=models.CharField(choices=[('Analyst', 'Analyst'), ('Field Engineer', 'Field Engineer'), ('Field Support', 'Field Support')], default='Field Support', max_length=32),
        ),
        migrations.AlterField(
            model_name='itsupport',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
