# Generated by Django 3.2.1 on 2021-08-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_auto_20210817_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='fax',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
