# Generated by Django 3.2.1 on 2021-08-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0006_auto_20210818_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='email',
        ),
        migrations.RemoveField(
            model_name='office',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='office',
            name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='fax',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
