# Generated by Django 3.2.1 on 2021-08-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0007_auto_20210818_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
