# Generated by Django 3.2.1 on 2021-08-19 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0009_auto_20210818_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='itsupport',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='network',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='router',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='computer',
            name='act_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date activated'),
        ),
        migrations.AddField(
            model_name='itsupport',
            name='act_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date activated'),
        ),
        migrations.AddField(
            model_name='network',
            name='act_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date activated'),
        ),
        migrations.AddField(
            model_name='router',
            name='act_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date activated'),
        ),
    ]
