# Generated by Django 3.2.1 on 2021-08-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0010_auto_20210819_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='pub_date',
        ),
    ]
