# Generated by Django 3.2.1 on 2021-08-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='type',
            field=models.CharField(choices=[('IPVPN', 'IPVPN'), ('VSAT', 'VSAT'), ('INTERNET', 'INTERNET'), ('METRONET', 'METRONET')], default='IPVPN', max_length=32),
        ),
    ]
