# Generated by Django 3.2.1 on 2021-08-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_auto_20210818_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='type',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER')], default='SILVER', max_length=16),
        ),
    ]
