# Generated by Django 3.2.1 on 2021-08-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0005_router_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='sid',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='sid',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='sti',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
