# Generated by Django 3.2.1 on 2021-08-24 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0014_auto_20210823_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboardapp.office'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='employee_name',
            field=models.CharField(default='someone', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboardapp.office'),
        ),
        migrations.AlterField(
            model_name='itsupport',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboardapp.office'),
        ),
        migrations.AlterField(
            model_name='network',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboardapp.office'),
        ),
        migrations.AlterField(
            model_name='office',
            name='sti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboardapp.sti'),
        ),
        migrations.AlterField(
            model_name='router',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboardapp.office'),
        ),
    ]
