# Generated by Django 3.2.6 on 2021-08-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensomit_itsupport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaitsupport',
            name='periode',
            field=models.CharField(max_length=6),
        ),
    ]
