# Generated by Django 3.2.6 on 2021-08-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensomit_itsupport', '0002_alter_slaitsupport_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaitsupport',
            name='total_ticket',
            field=models.IntegerField(null=True),
        ),
    ]
