# Generated by Django 3.2.6 on 2021-09-01 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensomit_itsupport', '0004_auto_20210825_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaitsupport',
            name='asman',
            field=models.CharField(max_length=32, verbose_name='Asman'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='biaya_restitusi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Biaya Restitusi (Rp)'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='durasi_over',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Durasi Over (Hour)'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='mulai_bekerja',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Mulai Bekerja'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='pencapaian_sla',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pencapaian SLA (%)'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='penempatan',
            field=models.CharField(max_length=64, verbose_name='Penempatan'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='periode',
            field=models.CharField(max_length=6, verbose_name='Periode'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='personil',
            field=models.CharField(max_length=128, verbose_name='Personil'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='spesifikasi',
            field=models.CharField(choices=[('AN', 'Analyst'), ('FE', 'Field Engineer'), ('FS', 'Field Support')], default='FS', max_length=32, verbose_name='Spesifikasi'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='tiket_over_sla',
            field=models.IntegerField(default=0, verbose_name='Tiket Over SLA'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='total_biaya',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Biaya (Rp)'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='total_ticket',
            field=models.IntegerField(default=0, verbose_name='Total Tiket'),
        ),
        migrations.AlterField(
            model_name='slaitsupport',
            name='unit',
            field=models.CharField(max_length=32, verbose_name='Unit'),
        ),
    ]
